import {fontField} from './fontField'

// Home page: hero photos, service blurbs, best-selling packages, testimonials
export default {
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  groups: [
    {name: 'heroes', title: '1. Big photo cards'},
    {name: 'packages', title: '2. Best selling packages'},
    {name: 'grey', title: '3. Our Services (grey section)'},
    {name: 'testimonials', title: '4. Featured testimonials'},
    {name: 'insta', title: '5. Instagram section'},
    {name: 'faqs', title: '6. FAQs section'},
    {name: 'visibility', title: 'Show / hide sections'},
  ],
  fields: [
    {
      name: 'heroCards',
      title: 'Big photo cards (top of home page)',
      type: 'array',
      group: 'heroes',
      description:
        'Add, remove, or reorder cards. Each card shows a thumbnail. Upload a photo for each.',
      options: {layout: 'grid'},
      of: [
        {
          type: 'object',
          name: 'heroCard',
          fields: [
            {name: 'title', type: 'string', title: 'Title on the photo', validation: (r) => r.required()},
            fontField(),
            {
              name: 'link',
              type: 'string',
              title: 'Where it goes when clicked',
              description: 'e.g. /newborn, /maternity, /family',
            },
            {
              name: 'image',
              type: 'image',
              title: 'Photo',
              options: {hotspot: true},
              fields: [{name: 'alt', type: 'string', title: 'Alt text'}],
            },
          ],
          preview: {
            select: {title: 'title', media: 'image'},
          },
        },
      ],
      validation: (r) => r.min(1).max(12),
    },
    {
      name: 'packagesTitle',
      title: 'Best selling packages — heading',
      type: 'string',
      group: 'packages',
      initialValue: 'BEST SELLING PACKAGES',
    },
    fontField({group: 'packages', name: 'packagesTitleFont', title: 'Font for this heading'}),
    {
      name: 'packagesQuoteLabel',
      title: 'Get a quote — button text',
      type: 'string',
      group: 'packages',
      initialValue: 'GET A QUOTE',
    },
    {
      name: 'bestSellingPackages',
      title: 'Best selling packages',
      type: 'array',
      group: 'packages',
      description: 'Add, edit, reorder, or delete package cards on the home page.',
      of: [
        {
          type: 'object',
          name: 'packageCard',
          fields: [
            {name: 'title', type: 'string', title: 'Package name', validation: (r) => r.required()},
            {
              name: 'link',
              type: 'string',
              title: 'Link (e.g. /maternity)',
              validation: (r) => r.required(),
            },
            {
              name: 'buttonLabel',
              type: 'string',
              title: 'Button text',
              initialValue: 'KNOW MORE',
            },
          ],
          preview: {
            select: {title: 'title', subtitle: 'link'},
          },
        },
      ],
    },
    {
      name: 'greyServicesTitle',
      title: 'Our Services — section title',
      type: 'string',
      group: 'grey',
      initialValue: 'Our Services',
    },
    fontField({group: 'grey', name: 'greyServicesTitleFont', title: 'Font for this heading'}),
    {
      name: 'greyServices',
      title: 'Our Services cards (grey section)',
      type: 'array',
      group: 'grey',
      description: 'These are the numbered cards (01, 02…). Add more or edit wording anytime.',
      of: [
        {
          type: 'object',
          name: 'greyService',
          fields: [
            {
              name: 'id',
              type: 'string',
              title: 'Number label',
              description: 'e.g. 01, 02, 03',
            },
            {name: 'title', type: 'string', title: 'Service name', validation: (r) => r.required()},
            {name: 'description', type: 'text', title: 'Short description', rows: 4},
            {name: 'link', type: 'string', title: 'Link (e.g. /newborn)'},
            {
              name: 'linkLabel',
              type: 'string',
              title: 'Link text',
              initialValue: 'READ MORE →',
            },
          ],
          preview: {
            select: {title: 'title', subtitle: 'id'},
          },
        },
      ],
    },
    {
      name: 'featuredTestimonialsHeading',
      title: 'Featured testimonials — heading',
      type: 'string',
      group: 'testimonials',
      initialValue: 'What clients say',
    },
    fontField({
      group: 'testimonials',
      name: 'featuredTestimonialsHeadingFont',
      title: 'Font for this heading',
    }),
    {
      name: 'featuredTestimonials',
      title: 'Featured testimonials on home page',
      type: 'array',
      group: 'testimonials',
      description: 'Pick which reviews appear on the home page (create Testimonials first).',
      of: [{type: 'reference', to: [{type: 'testimonial'}]}],
    },
    {
      name: 'instaHeading',
      title: 'Instagram section heading',
      type: 'string',
      group: 'insta',
      initialValue: 'WRIGGLY MOMENTS ON INSTA',
    },
    fontField({group: 'insta', name: 'instaHeadingFont', title: 'Font for this heading'}),
    {
      name: 'faqEyebrow',
      title: 'FAQs — small label above the title',
      type: 'string',
      group: 'faqs',
      initialValue: '----- FAQS -----',
    },
    {
      name: 'faqTitle',
      title: 'FAQs — section title',
      type: 'string',
      group: 'faqs',
      initialValue: 'Frequently Asked Questions',
    },
    fontField({group: 'faqs', name: 'faqTitleFont', title: 'Font for this heading'}),
    {
      name: 'homeFaqs',
      title: 'FAQs in this section',
      type: 'array',
      group: 'faqs',
      description:
        'Add existing FAQs (create them under FAQs in the sidebar first). Drag to reorder. Remove an item to hide it from this section (the FAQ itself is not deleted).',
      of: [{type: 'reference', to: [{type: 'faq'}]}],
    },
    {
      name: 'faqContactText',
      title: 'FAQs — text under the list',
      type: 'text',
      rows: 3,
      group: 'faqs',
      description: 'Leave blank to use the default “Got more questions…” line.',
    },
    {
      name: 'showHeroes',
      title: 'Show big photo cards',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
    {
      name: 'showPackages',
      title: 'Show best selling packages',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
    {
      name: 'showAbout',
      title: 'Show About Us strip',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
    {
      name: 'showGreyServices',
      title: 'Show Our Services (grey section)',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
    {
      name: 'showInsta',
      title: 'Show Instagram section',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
    {
      name: 'showFeaturedTestimonials',
      title: 'Show featured testimonials block',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
    {
      name: 'showTestimonials',
      title: 'Show testimonials carousel',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
    {
      name: 'showFaqs',
      title: 'Show FAQs section',
      type: 'boolean',
      group: 'visibility',
      initialValue: true,
    },
  ],
  preview: {
    prepare: () => ({title: 'Home Page'}),
  },
}
